### ISSUE TITLE
Skid

### ISSUE THREAD

**Issue by salahW3b** [lezetho/ticket-bot#1]
Salut mon skid comment sa va?

**Comment by salahW3b** [comment]
Ce bot ticket tu la skid

**Comment by salahW3b** [comment]
https://github.com/t3mq/ticket-bot repo original

**Comment by lezetho** [comment]
What? I credited him before already ;-;

**Comment by lezetho** [comment]
Also English only.

**Comment by lezetho** [comment]
@salahW3b First of all, I did not steal it. I updated it to a better version. Second, please use english only. Third, I updated the README.md of  this repo for your sake.
